# permissions for end users to view epsagons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: epsagon-viewer-role
rules:
- apiGroups:
  - integration.epsagon.com
  resources:
  - epsagons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integration.epsagon.com
  resources:
  - epsagons/status
  verbs:
  - get
