# permissions for end users to edit epsagons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: epsagon-editor-role
rules:
- apiGroups:
  - integration.epsagon.com
  resources:
  - epsagons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integration.epsagon.com
  resources:
  - epsagons/status
  verbs:
  - get
